[package]
name = "libipt"
version = "0.1.0"
authors = ["sum_catnip <catnip@catnip.fyi>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libipt-sys = "^0.1.4"
bitflags = "1.2.1"
num_enum = "0.4.2"